# Air configuration for WNC CLI development
# Documentation: https://github.com/air-verse/air

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/wnc ./cmd/main.go"
  bin = "tmp/wnc"
  full_bin = "tmp/wnc --help"
  exclude_dir = ["assets", "tmp", "vendor", "test_data", ".git", ".github", ".vscode", "node_modules", "dist", "build"]
  exclude_regex = ["_test\\.go"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[screen]
  keep_scroll = true
