# .goreleaser.yml for wnc CLI package

project_name: wnc
version: 2

# Distribution directory
dist: tmp/dist

# Build destination
github_urls:
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - main: cmd/main.go
    id: wnc
    binary: wnc
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    ldflags:
      - -X 'github.com/umatare5/wnc/pkg/version.Version={{ .Version }}'

archives:
  - name_template: '{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - "*.go"
      - "*.md"
      - "go.mod"
      - "go.sum"
      - "LICENSE"
      - "README.md"

# Docker configuration
dockers:
  - image_templates:
      - "ghcr.io/umatare5/wnc:latest-amd64"
      - "ghcr.io/umatare5/wnc:{{ .Tag }}-amd64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}-amd64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}.{{ .Minor }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool for managing Cisco C9800 Wireless Network Controllers"
      - "--label=org.opencontainers.image.url=https://github.com/umatare5/wnc"
      - "--label=org.opencontainers.image.source=https://github.com/umatare5/wnc"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - go.mod
      - go.sum
    goarch: amd64
  - image_templates:
      - "ghcr.io/umatare5/wnc:latest-arm64"
      - "ghcr.io/umatare5/wnc:{{ .Tag }}-arm64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}-arm64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}.{{ .Minor }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool for managing Cisco C9800 Wireless Network Controllers"
      - "--label=org.opencontainers.image.url=https://github.com/umatare5/wnc"
      - "--label=org.opencontainers.image.source=https://github.com/umatare5/wnc"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - go.mod
      - go.sum
    goarch: arm64

# Docker manifest for multi-platform images
docker_manifests:
  - name_template: "ghcr.io/umatare5/wnc:latest"
    image_templates:
      - "ghcr.io/umatare5/wnc:latest-amd64"
      - "ghcr.io/umatare5/wnc:latest-arm64"
  - name_template: "ghcr.io/umatare5/wnc:{{ .Tag }}"
    image_templates:
      - "ghcr.io/umatare5/wnc:{{ .Tag }}-amd64"
      - "ghcr.io/umatare5/wnc:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/umatare5/wnc:v{{ .Major }}"
    image_templates:
      - "ghcr.io/umatare5/wnc:v{{ .Major }}-amd64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/umatare5/wnc:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/umatare5/wnc:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/umatare5/wnc:v{{ .Major }}.{{ .Minor }}-arm64"

release:
  prerelease: auto
  draft: false
  replace_existing_draft: true
  header: |
    ## wnc v{{ .Version }}

    This release contains the CLI for interacting with Cisco Catalyst 9800 Wireless Network Controller.

    ### 🐳 Container Images
    ```bash
    # Latest version
    docker run --rm ghcr.io/umatare5/wnc:latest --help

    # Specific version
    docker run --rm ghcr.io/umatare5/wnc:{{ .Tag }} show overview --help

    # With environment variables
    docker run --rm -e WNC_CONTROLLERS="wnc.example.com:token" ghcr.io/umatare5/wnc:{{ .Tag }} show overview
    ```

    ### 📦 Binary Installation
    ```bash
    go install github.com/umatare5/wnc@v{{ .Version }}
    ```

    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/umatare5/wnc/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### 📚 Documentation
    - [README](https://github.com/umatare5/wnc/blob/{{ .Tag }}/README.md)
    - [CLI Reference](https://github.com/umatare5/wnc/blob/{{ .Tag }}/docs/CLI_REFERENCE.md)
    - [Container Registry](https://github.com/umatare5/wnc/pkgs/container/wnc)

# Generate checksums for source archives
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}_checksums.txt"

# Changelog configuration
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation updates
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other work
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'

# Metadata for Go proxy and pkg.go.dev
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
